# environmental parameters

# rain in m/s/m² within Interval of 0 and 25
float64 rain
# relative humidity in % within Interval of 0 and 1
float64 relHumidity
# air pressure in kPa within Interval of 87 and 105
float64 airPressure
# wind speed in m/s within Interval of 0 and 130
float64 windSpeed
# temperature in C° within Interval of -20 and 40
float64 temperature
# spray in m/s/m^2 within Interval of 0.3 and 0.7
float64 spray